apiVersion: v1
kind: Service
metadata:
  name: webapi-pod-service
spec:
  selector:
    app: webapi-pod-service  
  ports:
    - port: 8080 
      targetPort: 8080 
      nodePort: 30010 
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: webapi-pod-service
  labels:
    app: webapi-pod-service
spec:
  containers:
    - image: 192.168.10.130/jenkins_harbor/webapi-docker-cicd-k8s-pod-service:latest
      imagePullPolicy: IfNotPresent 
      name: webapi-pod-service-container
      ports:
        - containerPort: 8080